version: '2.0'
services:
  recursor:
      image: nativeit/pdns-recursor:${REVISION:-latest}
      environment:
        - PDNS_RECURSOR_API_KEY=${api-key}
      ports:
        - "2053:53"
        - "2053:53/udp"
        - "8082:8082"

  dnsdist:
    image: nativeit/dnsdist:${REVISION:-latest}
    environment:
      - DNSDIST_API_KEY=${api-key}
    links:
      - recursor
      - auth
    ports:
      - "3053:53"
      - "3053:53/udp"
      - "5199:5199"
      - "8083:8083"

  auth:
    image: nativeit/pdns-auth:${REVISION:-latest}
    environment:
      - PDNS_AUTH_API_KEY=${api-key}
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"

  dnscontrol:
    image: nativeit/dnscontrol:${REVISION:-latest}
    ports:
      - "8080:8080"


