---
#version: '2.0'
include:
  - .env
  - dockerdata/pdns.conf
services:
  recursor:
      image: nativeit/powerdns-recursor:${REVISION:-latest}
      environment:
        - PDNS_RECURSOR_API_KEY=${api-key}
      ports:
        - "2053:53"
        - "2053:53/udp"
        - "8082:8082"

  dnsdist:
    image: nativeit/powerdns-dnsdist:${REVISION:-latest}
    environment:
      - DNSDIST_API_KEY=${api-key}
    links:
      - recursor
      - auth
    ports:
      - "3053:53"
      - "3053:53/udp"
      - "5199:5199"
      - "8083:8083"

  auth:
    image: nativeit/powerdns-auth:${REVISION:-latest}
    environment:
      - PDNS_AUTH_API_KEY=${api-key}
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"
